repos:
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.45.0
  hooks:
    - id: terraform_fmt

- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v3.3.0
  hooks:
    - id: check-added-large-files
      exclude: ^infra/scoped/assets/swagger-ui
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-symlinks
    - id: detect-private-key
    - id: end-of-file-fixer
      exclude: ^infra/scoped/assets/swagger-ui
    - id: trailing-whitespace
      exclude: ^infra/scoped/assets/swagger-ui
    - id: check-json
      exclude: ^infra/scoped/task-definitions
    - id: check-yaml

- repo: https://github.com/detailyang/pre-commit-shell.git
  rev: v1.0.6
  hooks:
    - id: shell-lint
      args: [--format=json]

- repo: https://github.com/bemeurer/beautysh.git
  rev: 6.0.1
  hooks:
    - id: beautysh
      args: [--indent-size=2,--force-function-style=fnpar]
